apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ include "cruise-control.fullname" . }}-ui-config
data:
  config.csv: |
    {{ .Values.cruiseControl.envName }},{{ .Values.cruiseControl.kafkaClusterName }},https://{{ .Values.cruiseControl.ui.ingress.host }}/kafkacruisecontrol
