apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ include "cruise-control.fullname" . }}-brokers-config
data:
  brokerCapacity.json: |
    {
      "brokerCapacities": {{ .Values.cruiseControl.brokers.brokerCapacities | toJson }}
    }
