apiVersion: v1
kind: Service
metadata:
  name: {{ include "cruise-control.fullname" . }}-service
  labels:
    {{- include "cruise-control.labels" . | nindent 4 }}
spec:
  type: {{ .Values.cruiseControl.service.type | default "ClusterIP" }}
  selector:
    {{- include "cruise-control.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.cruiseControl.service.port | default 9090 }}
      targetPort: {{ .Values.cruiseControl.service.targetPort | default 9090 }}
